// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDccx2RuZnxaxmUY5C6ArbqZvrIlG-dfME',
    appId: '1:8903588731:web:ed12a2c9f07eefec2a1bde',
    messagingSenderId: '8903588731',
    projectId: 'masrofaty-6f0cb',
    authDomain: 'masrofaty-6f0cb.firebaseapp.com',
    storageBucket: 'masrofaty-6f0cb.appspot.com',
    measurementId: 'G-BZ8Y0PK4YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOZ2fIkqS2PcxjjugXB4Sk6Ya1wsdcV88',
    appId: '1:8903588731:android:787b8d8c54fbd6232a1bde',
    messagingSenderId: '8903588731',
    projectId: 'masrofaty-6f0cb',
    storageBucket: 'masrofaty-6f0cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNjN6L38iwZqV3laytjvXxRNWYaY9duG8',
    appId: '1:8903588731:ios:63b4c080cbffbeb22a1bde',
    messagingSenderId: '8903588731',
    projectId: 'masrofaty-6f0cb',
    storageBucket: 'masrofaty-6f0cb.appspot.com',
    iosBundleId: 'com.example.masrofaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNjN6L38iwZqV3laytjvXxRNWYaY9duG8',
    appId: '1:8903588731:ios:63b4c080cbffbeb22a1bde',
    messagingSenderId: '8903588731',
    projectId: 'masrofaty-6f0cb',
    storageBucket: 'masrofaty-6f0cb.appspot.com',
    iosBundleId: 'com.example.masrofaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDccx2RuZnxaxmUY5C6ArbqZvrIlG-dfME',
    appId: '1:8903588731:web:4a32aec5ecaabf892a1bde',
    messagingSenderId: '8903588731',
    projectId: 'masrofaty-6f0cb',
    authDomain: 'masrofaty-6f0cb.firebaseapp.com',
    storageBucket: 'masrofaty-6f0cb.appspot.com',
    measurementId: 'G-HKJFXF0EWT',
  );
}
